# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Manish Kumar"
resume_title:                   "DevOps Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "manishkadyar@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+91 7760275082 / 8618231316"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

# resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>As a DevOps Engineer at Oracle, I contribute to the continuous delivery and improvement of educational resources and learning experiences for Oracle University students. I work with a technical team to automate and optimize development and release processes, using tools such as Jenkins, Ansible, Kubernetes, and OCI.

I also have a strong background in SCCM administration and management, having performed installation, evaluation, maintenance, and problem resolution for the SCCM server and DPs, as well as release management deployments to over 35000 PCs globally in my previous role at Mphasis. I have multiple certifications in AWS and Oracle Cloud Infrastructure, and I am proficient in Python, Shell Scripting, SQL, and Selenium automation. I am passionate about learning new technologies and applying them to solve real-world problems, especially in the fields of ML and AI.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "http://twitter.com/jglovier"
  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
